apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
        - system:masters
      rolearn: arn:aws:iam::231772694704:role/UdacityFlaskDeployCBKubectlRole2
      username: build
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::231772694704:role/myEKSWorkerNodeRole
      username: system:node:{{EC2PrivateDNSName}}
